If:
  PathMatch: .*.cpp
CompileFlags:
  Compiler: x86_64-w64-mingw32-g++
  Add:
    - -D__CLANG_MAX_ALIGN_T_DEFINED
    - -Wno-vla-extension
    - -IC:/msys64/ucrt64/lib/gcc/x86_64-w64-mingw32/13.2.0/include
    - -IC:/msys64/ucrt64/lib/gcc/x86_64-w64-mingw32/13.2.0/include/c++
    - -IC:/msys64/ucrt64/lib/gcc/x86_64-w64-mingw32/13.2.0/include/c++/x86_64-w64-mingw32
    - -IC:/msys64/ucrt64/x86_64-w64-mingw32/include
    - -DLOCAL
    - -Wall
    - -O2
    - -Wextra
    - -Wshadow
    - -Wconversion
    - -Wfloat-equal
    - -Wno-unused-const-variable
    - -Wno-sign-conversion
    - -std=c++17
Index:
  Background: Skip
